#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal

# Source generated colors.
source "/home/zedjones/.cache/wal/colors.sh"
export HOME=/home/zedjones/
export XAUTHORITY=/home/zedjones/.Xauthority

reload_dunst() {
    pkill dunst && \
        dunst \
            -lb "$color0" \
            -nb "$color0" \
            -cb "$color0" \
            -lf "$color7"  \
            -nf "$color7"  \
            -cf "$color7"  \
            -fn "${DUNST_FONT:-ypn envypn 11}" \
            -geometry "${DUNST_SIZE:-500x20-40+40}" \
			-markup \
			-format "%s\n%b" \
			-show_age_threshold 60 \
			-follow mouse \
			-idle_threshold 120 \
			-align "center" \
			-padding 8 \
			-horizontal_padding 8 \
			-word_wrap yes \
			-lh 0 \
			-sep_height 2 \
			-stick_history  &
}

main() {
	sleep 2
	reload_dunst &
}

main >/dev/null 2>&1
