#!/bin/python3

import forecastio
api_key = "4bc10b6fd4106811bc5d4a1f05d57a76"
lon = -77.668721
lat = 43.083652

forecast = forecastio.load_forecast(api_key, lat, lon)
byHour = forecast.hourly()
if "." ==  byHour.summary[-1]:
	byHour.summary = byHour.summary[:-1]
print(byHour.summary +", "+ str(byHour.data[0].temperature) + " °F")
